import json
import os
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

logging.basicConfig(level=logging.INFO, format="%(levelname)s - %(message)s")

# --- Configuration ---
# Add the exact names of the institutions you want to monitor
WATCHLIST = [
    "Hemvati Nandan Bahuguna Garhwal University",
    "HNBGU"
]

# Pulling credentials from GitHub Secrets
EMAIL_SENDER = os.environ.get("EMAIL_SENDER")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")
EMAIL_RECEIVER = "admin@learnovaindia.org"  # Change this to your actual email if needed

def send_alert_email(new_retractions):
    """Compiles and sends an HTML email via SMTP."""
    if not EMAIL_SENDER or not EMAIL_PASSWORD:
        logging.warning("Email credentials missing. Cannot send alert. (Set EMAIL_SENDER and EMAIL_PASSWORD in GitHub Secrets)")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🚨 URGENT: {len(new_retractions)} New Retraction(s) Detected on Watchlist"
    msg["From"] = f"RetractRadar Sentinel <{EMAIL_SENDER}>"
    msg["To"] = EMAIL_RECEIVER

    # Build the HTML email body
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #dc2626;">RetractRadar Alert</h2>
        <p>The nightly scan has detected new retractions matching your institutional watchlist:</p>
        <hr style="border: 1px solid #eee;">
    """

    for art in new_retractions:
        title = art.get("title", "Untitled")
        doi = art.get("doi", "No DOI")
        year = art.get("year", "N/A")
        reason = art.get("reason_category", "Unspecified")
        unis = ", ".join(art.get("institutions", []))
        
        html += f"""
        <div style="margin-bottom: 20px;">
            <h3 style="margin-bottom: 5px; color: #111;">{title}</h3>
            <p style="margin: 2px 0; font-size: 14px;"><strong>Institutions:</strong> {unis}</p>
            <p style="margin: 2px 0; font-size: 14px;"><strong>Year:</strong> {year}</p>
            <p style="margin: 2px 0; font-size: 14px;"><strong>Category:</strong> <span style="color: #dc2626; font-weight: bold;">{reason}</span></p>
            <p style="margin: 2px 0; font-size: 14px;"><strong>DOI:</strong> <a href="{doi}">{doi}</a></p>
        </div>
        """

    html += """
        <hr style="border: 1px solid #eee;">
        <p style="font-size: 12px; color: #777;">This is an automated alert generated by your RetractRadar GitHub Action.</p>
      </body>
    </html>
    """

    msg.attach(MIMEText(html, "html"))

    # Connect to Gmail SMTP server
    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, msg.as_string())
        server.quit()
        logging.info("Successfully sent institutional alert email!")
    except Exception as e:
        logging.error(f"Failed to send email: {e}")

def run_sentinel():
    data_file = os.path.join("data", "retractions.json")
    memory_file = os.path.join("data", "alerted_dois.json")

    # Load current dataset
    if not os.path.exists(data_file):
        logging.warning("No retractions.json found. Skipping sentinel.")
        return
    with open(data_file, "r", encoding="utf-8") as f:
        articles = json.load(f)

    # Load memory of previously alerted DOIs
    alerted_dois = []
    if os.path.exists(memory_file):
        with open(memory_file, "r", encoding="utf-8") as f:
            alerted_dois = json.load(f)

    new_hits = []

    # Scan for matches on the watchlist
    for art in articles:
        doi = art.get("doi")
        if not doi or doi in alerted_dois:
            continue  # Skip if we have already alerted on this DOI or if it lacks a DOI

        institutions = art.get("institutions", [])
        
        # Check if any watchlist institution is in the article's institution list
        if any(watched_uni.lower() in [u.lower() for u in institutions] for watched_uni in WATCHLIST):
            new_hits.append(art)
            alerted_dois.append(doi)

    # If new hits found, trigger email and update memory
    if new_hits:
        logging.info(f"Found {len(new_hits)} new retractions for watchlist. Sending alert...")
        send_alert_email(new_hits)
        
        # Save updated memory so we don't alert on these again tomorrow
        os.makedirs("data", exist_ok=True)
        with open(memory_file, "w", encoding="utf-8") as f:
            json.dump(alerted_dois, f)
    else:
        logging.info("No new retractions found for watched institutions today.")

if __name__ == "__main__":
    run_sentinel()
